{{ if eq .Values.config.admissionControl.createService true }}
apiVersion: v1
kind: Secret
data:
  ca.pem: |-
{{ (.Files.Get "secrets/ca.pem") | b64enc | indent 4 }}
  admission-control-cert.pem: |-
{{ (.Files.Get secrets/admission-control-cert.pem") | b64enc | indent 4 }}
  admission-control-key.pem: |-
{{ (.Files.Get "secrets/admission-control-key.pem") | b64enc | indent 4 }}
metadata:
  labels:
    auto-upgrade.stackrox.io/component: sensor
  name: admission-control-tls
  namespace: stackrox
type: Opaque
{{ end }}