{{if ne ".Values.collectionMethod" "NO_COLLECTION"}}
apiVersion: v1
kind: Secret
data:
  ca.pem: |-
{{ .Files.Get "secrets/ca.pem" | b64enc | indent 4 }}
  collector-cert.pem: |-
{{ .Files.Get "secrets/collector-cert.pem" | b64enc | indent 4 }}
  collector-key.pem: |-
{{ .Files.Get "secrets/collector-key.pem" | b64enc | indent 4 }}
metadata:
  labels:
    auto-upgrade.stackrox.io/component: sensor
  name: collector-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: |-
{{ .Files.Get "secrets/collector-imagepull-secret" | indent 4 }}
metadata:
  name: collector-stackrox
  namespace: stackrox
type: kubernetes.io/dockerconfigjson
{{ end }}
