licenseKey: null # string
imagePullSecrets:
  username: null # string
  password: null # string
  allowNone: null # bool
  useExisting: null # string | [string]
  useFromDefaultServiceAccount: null # bool
image:
  registry: null # string
env:
  openshift: null # bool
  istio: null # bool
  platform: null # string
  offlineMode: null # bool
  proxyConfig: null # string | dict
ca:
  cert: null # string
  key: null # string
  generate: null # bool
central:
  disableTelemetry: null # bool
  config: null # string | dict
  endpointsConfig: null # string | dict
  nodeSelector: null # string | dict
  jwtSigner:
    key: null # string
    generate: null # bool
  serviceTLS:
    cert: null # string
    key: null # string
    generate: null # bool
  defaultTLS:
    cert: null # string
    key: null # string
  image:
    registry: null # string
    name: null # string
    tag: null # string
    fullRef: null # string
  adminPassword:
    value: null # string
    generate: null # bool
    htpasswd: null # string
  resources: null # string | dict
  persistence:
    hostPath: null # string
    persistentVolumeClaim:
      claimName: null # string
      createClaim: null # bool
      storageClass: null # string
      size: null # int | string
    none: null # bool
  exposure:
    loadBalancer:
      enabled: null # bool
      port: null # int
    nodePort:
      enabled: null # bool
      port: null # int
    route:
      enabled: null # bool

scanner:
  disable: null # bool
  replicas: null # int
  logLevel: null # string
  autoscaling:
    disable: null # bool
    minReplicas: null # int
    maxReplicas: null # int
  resources: null # string | dict
  image:
    registry: null # string
    name: null # string
    tag: null # string
    fullRef: null # string
  dbImage:
    registry: null # string
    name: null # string
    tag: null # string
    fullRef: null # string
  dbResources: null # string | dict
  dbPassword:
    value: null # string
    generate: null # bool
  serviceTLS:
    cert: null # string
    key: null # string
    generate: null # bool
  dbServiceTLS:
    cert: null # string
    key: null # string
    generate: null # bool
customize:
  labels: {} # dict
  annotations: {} # dict
  podLabels: {} # dict
  podAnnotations: {} # dict
  envVars: {} # dict
  central:
    labels: {} # dict
    annotations: {} # dict
    podLabels: {} # dict
    podAnnotations: {} # dict
    envVars: {} # dict
  scanner:
    labels: {} # dict
    annotations: {} # dict
    podLabels: {} # dict
    podAnnotations: {} # dict
    envVars: {} # dict
  scanner-db:
    labels: {} # dict
    annotations: {} # dict
    podLabels: {} # dict
    podAnnotations: {} # dict
    envVars: {} # dict
  other: {} # dict
allowNonstandardNamespace: null # bool
allowNonstandardReleaseName: null # bool
meta:
  useLookup: null # bool
  fileOverrides: {} # dict
  apiServer:
    version: null # string
    overrideAPIResources: null # [string]
    extraAPIResources: null # [string]
  noCreateStorageClass: null # bool
