licenseKey: true
imagePullSecrets:
  username: true
  password: true
env:
  proxyConfig: true
ca:
  cert: true
  key: true
central:
  config: true
  endpointsConfig: true
  nodeSelector: true
  jwtSigner:
    key: true
  serviceTLS:
    cert: true
    key: true
  defaultTLS:
    cert: true
    key: true
  adminPassword:
    value: true
    htpasswd: true
  resources: true
  db:
    postgresConfig: true
    hbaConfig: true
    nodeSelector: true
    serviceTLS:
      cert: true
      key: true
    password:
      value: true
    resources: true
scanner:
  resources: true
  dbResources: true
  nodeSelector: true
  dbNodeSelector: true
  dbPassword:
    value: true
  serviceTLS:
    cert: true
    key: true
  dbServiceTLS:
    cert: true
    key: true
scannerV4:
  indexer:
    resources: true
  matcher:
    resources: true
  db:
    resources: true
    postgresConfig: true
    hbaConfig: true
    password:
      value: true
