# OSD (openshift dedicated) clusters disallow updates to the 'anyuid' scc.
#
# This 'qatest-anyuid' resource is a copy of 'anyuid' as gathered via:
# `oc get scc anyuid -o yaml | kfilter`
#
# The 'qatest-anyuid' is augmented in test setup in:
# //stackrox/qa-tests-backend/src/main/groovy/orchestratormanager/OpenShift.groovy

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: qatest-anyuid
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubernetes.io/description: qatest-anyuid is a copy of anyuid to be
      augmented with capabilities required for testing. The Groovy based test
      harness augments qatest-anyuid capabilities in the test environment setup
      stage.
    release.openshift.io/create-only: "false"
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: false
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: ["*"]
allowedUnsafeSysctls: ["*"]
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: [system:serviceaccount:stackrox:default]
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
