# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'ui/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    # always update package.json files to match new version for any package in UI monorepo
    versioning-strategy: increase
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - "stackrox/ui-dep-updaters"


  - package-ecosystem: 'gradle'
    directory: 'qa-tests-backend/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    labels:
      - "ci-all-qa-tests"
      - "dependencies"
    reviewers:
      - "stackrox/backend-dep-updaters"

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    labels:
      - "ci-all-qa-tests"
      - "dependencies"
    reviewers:
      - "stackrox/backend-dep-updaters"
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: 'gomod'
    directory: '/tools/linters/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    reviewers:
      - "stackrox/backend-dep-updaters"

  - package-ecosystem: 'gomod'
    directory: '/tools/test/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    reviewers:
      - "stackrox/backend-dep-updaters"

  - package-ecosystem: 'gomod'
    directory: '/operator/tools/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 1
    labels:
    - "dependencies"
    reviewers:
    - "stackrox/backend-dep-updaters"

  - package-ecosystem: 'docker'
    directory: 'operator/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 1
    labels:
    - "dependencies"
    reviewers:
    - "stackrox/backend-dep-updaters"

  - package-ecosystem: 'docker'
    directory: 'image/rhel'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 1
    labels:
    - "ci-all-qa-tests"
    - "dependencies"
    reviewers:
    - "stackrox/backend-dep-updaters"

  - package-ecosystem: 'docker'
    directory: 'image/postgres'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 1
    labels:
    - "ci-all-qa-tests"
    - "dependencies"
    reviewers:
    - "stackrox/backend-dep-updaters"
