# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'ui/apps/platform'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    # always update package.json files to match new version for any package in UI monorepo
    versioning-strategy: increase
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "area/ui"
      - "auto-retest"
    reviewers:
      - "stackrox/ui-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gradle'
    directory: 'qa-tests-backend/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    labels:
      - "ci-all-qa-tests"
      - "dependencies"
      - "auto-merge"
      - "auto-retest"
    reviewers:
      - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 9
    labels:
      - "ci-all-qa-tests"
      - "dependencies"
      - "auto-merge"
      - "auto-retest"
    reviewers:
      - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    ignore:
      # k8s minor releases usually bumps go version to the latest one which we do not use.
      - dependency-name: "k8s.io/*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "github.com/aws/aws-sdk-go"
        update-types: ["version-update:semver-patch"]
      # The Scanner team wants full control over ClairCore updates,
      # so we ensure Scanner V4 does not have any unexpected changes.
      - dependency-name: "github.com/quay/claircore"
    groups:
      k8s.io:
        update-types:
          - "patch"
        patterns:
          - "k8s.io/*"
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go-v2/*"

  - package-ecosystem: 'gomod'
    directory: '/tools/linters/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "auto-merge"
    - "auto-retest"
    reviewers:
      - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/tools/proto/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/tools/test/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "auto-merge"
    - "auto-retest"
    reviewers:
      - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/tools/retest/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/operator/tools/controller-gen'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/operator"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/operator/tools/envtest/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/operator"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/operator/tools/kustomize/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/operator"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/operator/tools/kuttl/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/operator"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/operator/tools/operator-sdk/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/operator"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      operator-framework:
        patterns:
        - "github.com/operator-framework/*"

  - package-ecosystem: 'gomod'
    directory: '/operator/tools/yq/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/operator"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'gomod'
    directory: '/scanner/tools/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/scanner"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/scanner"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'docker'
    directory: 'operator/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "dependencies"
    - "area/operator"
    - "auto-merge"
    - "auto-retest"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'docker'
    directory: 'image/rhel'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "ci-all-qa-tests"
    - "dependencies"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'docker'
    directory: 'image/postgres'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "ci-all-qa-tests"
    - "dependencies"
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'docker'
    directory: 'scanner/image/scanner'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "ci-all-qa-tests"
    - "dependencies"
    reviewers:
    - "stackrox/scanner"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: 'docker'
    directory: 'scanner/image/db'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    labels:
    - "ci-all-qa-tests"
    - "dependencies"
    reviewers:
    - "stackrox/scanner"
    commit-message:
      include: scope
      prefix: chore

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
          - "actions/*"

  # Below configuration is workaround for dependabot issue
  # about local actions in .github/actions/ are not checked
  # https://github.com/dependabot/dependabot-core/issues/6345

  - package-ecosystem: github-actions
    directory: /.github/actions/cache-go-dependencies
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"

  - package-ecosystem: github-actions
    directory: /.github/actions/cache-gradle-dependencies
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"

  - package-ecosystem: github-actions
    directory: /.github/actions/cache-ui-dependencies
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"

  - package-ecosystem: github-actions
    directory: /.github/actions/download-artifact-with-retry
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"

  - package-ecosystem: github-actions
    directory: /.github/actions/handle-tagged-build
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"


  - package-ecosystem: github-actions
    directory: /.github/actions/job-preamble
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"

  - package-ecosystem: github-actions
    directory: /.github/actions/junit2jira
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"

  - package-ecosystem: github-actions
    directory: /.github/actions/upload-artifact-with-retry
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
    - "stackrox/backend-dep-updaters"
    commit-message:
      include: scope
      prefix: chore
    groups:
      actions:
        patterns:
        - "actions/*"
