apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: metrics
    port: 9090
    targetPort: 9090
  - name: grafana
    port: 8443
    targetPort: 8443
  selector:
    app: monitoring
  type: ClusterIP
