# Adds namespace to all resources.
namespace: stackrox-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: stackrox-operator-

# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    app: stackrox-operator

resources:
- ../../default
