apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scanner-tls
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
{{if not .Values.gcpMarketplace}}
  annotations:
    "helm.sh/hook": "pre-install"
{{end}}
{{toYaml .Values.secrets.tls}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: scanner-db-tls
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: stackrox
{{if not .Values.gcpMarketplace}}
  annotations:
    "helm.sh/hook": "pre-install"
{{end}}
{{toYaml .Values.secrets.dbtls}}