# Default values for rhacs-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  # Each item in images should contain `repository` and `tag` key
  # example:
  #   images:
  #   - deploymentName: rhacs-operator-manager-4.0.0
  #     repository: quay.io/rhacs-eng/stackrox-operator
  #     tag: 4.0.0
  #   - deploymentName: rhacs-operator-manager-4.0.1
  #     repository: quay.io/rhacs-eng/stackrox-operator
  #     tag: 4.0.1
  images: []
  # TODO: add values for resource limits and requests for both proxy and manager container
  # TODO: add value for kube-rbac-proxy image

  # In outer mode, the Operator reconciles Central CRs as well as the inner Operator.
  # In non-outer mode (inner mode), the Operator reconciles Secured Cluster CRs.
  outerMode: false
