configurations:
- kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../scorecard
images:
- name: scorecard-test
  newName: quay.io/operator-framework/scorecard-test
  newTag: v1.24.1
