# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/rhacs-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard-versioned

# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
# The patch is only required for OLM-based installations because OLM creates and mounts these volumes itself.
# In other words, the patch will NOT be executed for non-OLM-based installations.
# Should be kept in sync with operator/config/default/manager_webhook_patch.yaml.
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
    namespace: system
  patch: |-
    # Remove the manager container's "cert" volumeMount, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing containers/volumeMounts in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/0
    # Remove the "cert" volume, since OLM will create and mount a set of certs.
    # Update the indices in this path if adding or removing volumes in the manager's Deployment.
    - op: remove
      path: /spec/template/spec/volumes/0
