apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
    app: sensor
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    owner: stackrox
    email: support@stackrox.com
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: sensor
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: stackrox
      labels:
        app: sensor
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "8443,9443"
    spec:
      {{if eq .Values.cluster.type "OPENSHIFT_CLUSTER"}}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 25
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/compute
                    operator: In
                    values:
                    - "true"
            - weight: 75
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: NotIn
                    values:
                    - "true"
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: NotIn
                    values:
                    - "true"
      {{- end}}
      securityContext:
        runAsUser: 4000
        fsGroup: 4000
      {{if eq .Values.cluster.type "KUBERNETES_CLUSTER" }}
      imagePullSecrets:
        - name: stackrox
      {{- end}}
      serviceAccount: sensor
      containers:
      - image: {{ printf "%s/%s:!!.ImageTag!!" .Values.image.registry.main .Values.image.repository.main }}
        name: sensor
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /admissioncontroller
            port: 9443
        ports:
          - containerPort: 8443
            name: api
          - containerPort: 9443
            name: webhook
        command:
          - kubernetes-sensor
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        env:
        - name: ROX_CENTRAL_ENDPOINT
          value: {{.Values.endpoint.central}}
        - name: ROX_ADVERTISED_ENDPOINT
          value: {{.Values.endpoint.advertised}}
          {{if eq .Values.cluster.type "OPENSHIFT_CLUSTER"}}
        - name: ROX_OPENSHIFT_API
          value: "true"
          {{- end}}
        {{ range .Values.envVars -}}
        - name: {{ .name }}
          value: {{ .value | quote}}
        {{ end }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log/stackrox/
        - name: sensor-etc-ssl-volume
          mountPath: /etc/ssl/
        - name: sensor-etc-pki-volume
          mountPath: /etc/pki/ca-trust/
        - name: certs
          mountPath: /run/secrets/stackrox.io/certs/
          readOnly: true
        - name: additional-ca-volume
          mountPath: /usr/local/share/ca-certificates/
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: sensor-tls
          items:
          - key: sensor-cert.pem
            path: cert.pem
          - key: sensor-key.pem
            path: key.pem
          - key: ca.pem
            path: ca.pem
      - name: sensor-etc-ssl-volume
        emptyDir: {}
      - name: sensor-etc-pki-volume
        emptyDir: {}
      - name: additional-ca-volume
        secret:
          secretName: additional-ca-sensor
          optional: true
      - name: varlog
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sensor
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
    auto-upgrade.stackrox.io/component: "sensor"
spec:
  ports:
  - name: https
    port: 443
    targetPort: api
    protocol: TCP
  selector:
    app: sensor
  type: ClusterIP
  sessionAffinity: None

{{ if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3/DestinationRule" }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sensor-internal-no-istio-mtls
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
  annotations:
    stackrox.io/description: "Disable Istio mTLS for port 443, since StackRox services use built-in mTLS."
spec:
  host: sensor.stackrox.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: DISABLE
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-webhook
  namespace: stackrox
  labels:
    app.kubernetes.io/name: stackrox
    auto-upgrade.stackrox.io/component: "sensor"
spec:
  ports:
  - name: https
    port: 443
    targetPort: webhook
    protocol: TCP
  selector:
    app: sensor
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: stackrox
    service: collector
    app: collector
    auto-upgrade.stackrox.io/component: "sensor"
  name: collector
  namespace: stackrox
spec:
  selector:
    matchLabels:
      service: collector
  template:
    metadata:
      labels:
        service: collector
        app: collector
      namespace: stackrox
    spec:
      {{- if ne .Values.config.disableTaintTolerations true}}
      tolerations:
      - operator: "Exists"
      {{- end}}
      serviceAccount: collector
      containers:
{{ if ne .Values.config.collectionMethod "NO_COLLECTION"}}
      - name: collector
        image: {{ printf "%s/%s:!!.CollectorImageTag!!" .Values.image.registry.collector .Values.image.repository.collector }}
        imagePullPolicy: Always
        env:
        - name: COLLECTOR_CONFIG
          value: '{"tlsConfig":{"caCertPath":"/var/run/secrets/stackrox.io/certs/ca.pem","clientCertPath":"/var/run/secrets/stackrox.io/certs/cert.pem","clientKeyPath":"/var/run/secrets/stackrox.io/certs/key.pem"}}'
        - name: COLLECTION_METHOD
          value: {{ .Values.config.collectionMethod }}
        - name: GRPC_SERVER
          value: {{ .Values.endpoint.advertised }}
        resources:
          limits:
            cpu: 750m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 320Mi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
          privileged: true
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: var-run-docker-sock
          readOnly: true
        - mountPath: /host/proc
          name: proc-ro
          readOnly: true
        - mountPath: /module
          name: tmpfs-module
        - mountPath: /host/etc
          name: etc-ro
          readOnly: true
        - mountPath: /host/usr/lib
          name: usr-lib-ro
          readOnly: true
        - mountPath: /host/sys
          name: sys-ro
          readOnly: true
        - mountPath: /host/dev
          name: dev-ro
          readOnly: true
        - mountPath: /run/secrets/stackrox.io/certs/
          name: certs
          readOnly: true
{{ end }}
      - command:
        - stackrox/compliance
        env:
        - name: ROX_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: ROX_ADVERTISED_ENDPOINT
          value: {{ .Values.endpoint.advertised }}
        image: {{ printf "%s/%s:!!.ImageTag!!" .Values.image.registry.main .Values.image.repository.main }}
        imagePullPolicy: IfNotPresent
        name: compliance
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: true
          seLinuxOptions:
            type: "container_runtime_t"
        volumeMounts:
        - mountPath: /etc/ssl/
          name: etc-ssl
        - mountPath: /etc/pki/ca-trust/
          name: etc-pki-volume
        - mountPath: /host
          name: host-root-ro
          readOnly: true
        - mountPath: /run/secrets/stackrox.io/certs/
          name: certs
          readOnly: true
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: var-run-docker-sock
      - hostPath:
          path: /proc
        name: proc-ro
      - emptyDir:
          medium: Memory
        name: tmpfs-module
      - hostPath: 
          path: /etc
        name: etc-ro
      - hostPath: 
          path: /usr/lib
        name: usr-lib-ro
      - hostPath: 
          path: /sys/
        name: sys-ro
      - hostPath:
          path: /dev
        name: dev-ro
      - name: certs
        secret:
          secretName: collector-tls
          items:
          - key: collector-cert.pem
            path: cert.pem
          - key: collector-key.pem
            path: key.pem
          - key: ca.pem
            path: ca.pem
      - hostPath:
          path: /
        name: host-root-ro
      - name: etc-ssl
        emptyDir: {}
      - name: etc-pki-volume
        emptyDir: {}
