{{- include "srox.init" . -}}


{{- $name := "stackrox-gke-ssd" -}}
{{- if has $name ._rox._state.referencedStorageClasses -}}
  {{- $lookupOut := dict -}}
  {{- $globalName := include "srox.globalResourceName" (list . $name) -}}
  {{- $_ := include "srox.safeLookup" (list . $lookupOut "storage.k8s.io/v1" "StorageClass" "" $globalName) -}}
  {{- if and (not $lookupOut.result) (or .Release.IsInstall $lookupOut.reliable) (not ._rox.meta.noCreateStorageClass) -}}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $globalName }}
  labels:
    {{- include "srox.labels" (list . "storageclass" $name) | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "storageclass" $name) | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
    "helm.sh/hook-delete-policy": never
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

  {{- end }}
{{- end }}
