{{- include "srox.init" . -}}

{{- if or ._rox.createSecrets (and (kindIs "invalid" ._rox.createSecrets) (or ._rox.admissionControl.serviceTLS._cert ._rox.admissionControl.serviceTLS._key)) }}

{{- if not (and ._rox.ca._cert ._rox.admissionControl.serviceTLS._cert ._rox.admissionControl.serviceTLS._key) }}
  {{ include "srox.fail" "Requested secret creation, but not all of CA certificate, admission control certificate, admission control private key are available. Set the 'createSecrets' config option to false if you do not want secrets to be created." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: admission-control-tls
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "admission-control-tls") | nindent 4 }}
    auto-upgrade.stackrox.io/component: sensor
  annotations:
    {{- include "srox.annotations" (list . "secret" "admission-control-tls") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  ca.pem: |
    {{- ._rox.ca._cert | nindent 4 }}
  admission-control-cert.pem: |
    {{- ._rox.admissionControl.serviceTLS._cert | nindent 4 }}
  admission-control-key.pem: |
    {{- ._rox.admissionControl.serviceTLS._key | nindent 4 }}

{{- end }}
