{{- include "srox.init" . -}}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: collector-no-ingress
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "networkpolicy" "collector-no-ingress") | nindent 4 }}
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "networkpolicy" "collector-no-ingress") | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: collector
  policyTypes:
    - Ingress

{{ if ._rox.collector.exposeMonitoring }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: collector-monitoring
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "networkpolicy" "collector-monitoring") | nindent 4 }}
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "networkpolicy" "collector-monitoring") | nindent 4 }}
spec:
  ingress:
  - ports:
    - port: 9090
      protocol: TCP
    - port: 9092
      protocol: TCP
    - port: 9094
      protocol: TCP
  podSelector:
    matchLabels:
      app: collector
  policyTypes:
    - Ingress
{{ end }}
