{{- include "srox.init" . -}}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "srox.labels" (list . "daemonset" "collector") | nindent 4 }}
    service: collector
    app: collector
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "daemonset" "collector") | nindent 4 }}
  name: collector
  namespace: {{ ._rox._namespace }}
spec:
  selector:
    matchLabels:
      service: collector
  template:
    metadata:
      namespace: {{ ._rox._namespace }}
      labels:
        service: collector
        app: collector
        {{- include "srox.podLabels" (list . "daemonset" "collector") | nindent 8 }}
      annotations:
        {{- include "srox.podAnnotations" (list . "daemonset" "collector") | nindent 8 }}
        openshift.io/required-scc: stackrox-collector
    spec:
      {{- if not ._rox.collector.disableTaintTolerations }}
      tolerations:
      {{- toYaml ._rox.collector.tolerations | nindent 6 }}
      {{- end }}
      {{- if ._rox.collector._nodeSelector }}
      nodeSelector:
        {{- ._rox.collector._nodeSelector | nindent 8 }}
      {{- end}}
      serviceAccountName: collector
      containers:
      {{- if ne ._rox.collector.collectionMethod "NO_COLLECTION"}}
      - name: collector
        image: {{ quote ._rox.image.collector.fullRef }}
        imagePullPolicy: {{ ._rox.collector.imagePullPolicy }}
        {{- if ._rox.collector.exposeMonitoring }}
        ports:
          - containerPort: 9090
            name: monitoring
        {{- end }}
        env:
        - name: COLLECTOR_CONFIG
          value: '{"tlsConfig":{"caCertPath":"/var/run/secrets/stackrox.io/certs/ca.pem","clientCertPath":"/var/run/secrets/stackrox.io/certs/cert.pem","clientKeyPath":"/var/run/secrets/stackrox.io/certs/key.pem"}}'
        - name: COLLECTION_METHOD
          value: {{ ._rox.collector.collectionMethod }}
        - name: GRPC_SERVER
          value: {{ ._rox.sensor.endpoint }}
        - name: SNI_HOSTNAME
          value: "sensor.stackrox.svc"
        {{- include "srox.envVars" (list . "daemonset" "collector" "collector") | nindent 8 }}
        resources:
          {{- ._rox.collector._resources | nindent 10 }}
        securityContext:
          capabilities:
            drop:
            - NET_RAW
          privileged: true
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /host/proc
          name: proc-ro
          readOnly: true
          mountPropagation: HostToContainer
        - mountPath: /module
          name: tmpfs-module
        - mountPath: /host/etc
          name: etc-ro
          readOnly: true
          mountPropagation: HostToContainer
        - mountPath: /host/usr/lib
          name: usr-lib-ro
          readOnly: true
          mountPropagation: HostToContainer
        - mountPath: /host/sys
          name: sys-ro
          readOnly: true
          mountPropagation: HostToContainer
        - mountPath: /host/dev
          name: dev-ro
          readOnly: true
          mountPropagation: HostToContainer
        - mountPath: /run/secrets/stackrox.io/certs/
          name: certs
          readOnly: true
      {{- end }}
      - command:
        - stackrox/compliance
        env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ROX_CALL_NODE_INVENTORY_ENABLED
          value: {{ if eq ._rox.env.openshift 4 }}"true"{{ else }}"false"{{ end }}
        - name: ROX_METRICS_PORT
        {{- if ._rox.collector.exposeMonitoring }}
          value: ":9091"
        {{- else}}
          value: "disabled"
        {{- end }}
        - name: ROX_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: ROX_ADVERTISED_ENDPOINT
          value: {{ quote ._rox.sensor.endpoint }}
        - name: ROX_NODE_SCANNING_ENDPOINT
          value: {{ quote ._rox.collector.nodescanningEndpoint }}
        {{- include "srox.envVars" (list . "daemonset" "collector" "compliance") | nindent 8 }}
        image: {{ quote ._rox.image.main.fullRef }}
        imagePullPolicy: {{ ._rox.collector.complianceImagePullPolicy }}
        name: compliance
        {{- if ._rox.collector.exposeMonitoring }}
        ports:
        - containerPort: 9091
          name: monitoring
        {{- end }}
        resources:
          {{- ._rox.collector._complianceResources | nindent 10 }}
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: true
          {{ if not ._rox.collector.disableSELinuxOptions }}
          seLinuxOptions:
            type: {{ ._rox.collector.seLinuxOptionsType | default "container_runtime_t" | quote }}
          {{ end }}
        volumeMounts:
        - mountPath: /etc/ssl/
          name: etc-ssl
        - mountPath: /etc/pki/ca-trust/
          name: etc-pki-volume
        - mountPath: /host
          name: host-root-ro
          readOnly: true
          mountPropagation: HostToContainer
        - mountPath: /run/secrets/stackrox.io/certs/
          name: certs
          readOnly: true
      {{- if eq ._rox.env.openshift 4 }}
      - name: node-inventory
        image: {{ quote ._rox.image.scanner.fullRef }}
        imagePullPolicy: IfNotPresent
        command: ["/scanner", "--nodeinventory", "--config=", ""]
        ports:
          - containerPort: 8444
            name: grpc
        resources:
          {{- ._rox.collector._nodeScanningResources | nindent 10 }}
        env:
        - name: ROX_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        {{- include "srox.envVars" (list . "daemonset" "collector" "node-inventory") | nindent 8 }}
        volumeMounts:
         - mountPath: /host
           name: host-root-ro
           readOnly: true
           mountPropagation: HostToContainer
         - mountPath: /tmp/
           name: tmp-volume
         - mountPath: /cache
           name: cache-volume
      {{- end }}
      volumes:
      - hostPath:
          path: /proc
        name: proc-ro
      - emptyDir:
          medium: Memory
        name: tmpfs-module
      - hostPath:
          path: /etc
        name: etc-ro
      - hostPath:
          path: /usr/lib
        name: usr-lib-ro
      - hostPath:
          path: /sys/
        name: sys-ro
      - hostPath:
          path: /dev
        name: dev-ro
      - name: certs
        secret:
          secretName: collector-tls
          items:
          - key: collector-cert.pem
            path: cert.pem
          - key: collector-key.pem
            path: key.pem
          - key: ca.pem
            path: ca.pem
      - hostPath:
          path: /
        name: host-root-ro
      - name: etc-ssl
        emptyDir: {}
      - name: etc-pki-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
      - name: cache-volume
        emptyDir:
          sizeLimit: 200Mi
