{{- include "srox.init" . -}}

{{- if ._rox.env.openshift }}
{{- if ._rox.system.createSCCs }}

apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: stackrox-sensor
  labels:
    {{- include "srox.labels" (list . "securitycontextconstraints" "stackrox-sensor") | nindent 4 }}
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "securitycontextconstraints" "stackrox-sensor") | nindent 4 }}
    kubernetes.io/description: stackrox-sensor is the security constraint for the sensor
users:
  - system:serviceaccount:{{ ._rox._namespace }}:sensor
  - system:serviceaccount:{{ ._rox._namespace }}:sensor-upgrader
priority: 0
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: RunAsAny
groups: []
readOnlyRootFilesystem: true
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
requiredDropCapabilities: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - secret

---

{{- end }}

# Despite the lack of 'anyuid' in this role, the name is kept as 'use-anyuid-scc' to avoid manual upgrade steps
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-anyuid-scc
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "role" "use-anyuid-scc") | nindent 4 }}
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "role" "use-anyuid-scc") | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - nonroot-v2
  - nonroot
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sensor-use-scc
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "sensor-use-scc") | nindent 4 }}
    auto-upgrade.stackrox.io/component: "sensor"
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "sensor-use-scc") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-anyuid-scc
subjects:
- kind: ServiceAccount
  name: sensor
  namespace: {{ ._rox._namespace }}
- kind: ServiceAccount
  name: sensor-upgrader
  namespace: {{ ._rox._namespace }}

{{- end }}
