{{- include "srox.init" . -}}

{{- if ._rox.createUpgraderServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensor-upgrader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "serviceaccount" "sensor-upgrader") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "serviceaccount" "sensor-upgrader") | nindent 4 }}
imagePullSecrets:
- name: stackrox
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stackrox:upgrade-sensors
  labels:
    {{- include "srox.labels" (list . "clusterrolebinding" "stackrox:upgrade-sensors") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "clusterrolebinding" "stackrox:upgrade-sensors") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: sensor-upgrader
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
