{{- include "srox.init" . -}}
{{- if and (not ._rox.scannerV4.disable) (not ._rox.scannerV4.indexer.disable) -}}
{{- if not ._rox.scannerV4.indexer.autoscaling.disable -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scanner-v4-indexer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "horizontalpodautoscaler" "scanner-v4-indexer") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "horizontalpodautoscaler" "scanner-v4-indexer") | nindent 4 }}
spec:
  minReplicas: {{ ._rox.scannerV4.indexer.autoscaling.minReplicas }}
  maxReplicas: {{ ._rox.scannerV4.indexer.autoscaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scanner-v4-indexer
  targetCPUUtilizationPercentage: 150
{{ end -}}
{{ end -}}
