{{- include "srox.init" . -}}
{{- if and (not ._rox.scannerV4.disable) (not ._rox.scannerV4.matcher.disable) -}}
{{- if and ._rox.scannerV4.matcher._serviceTLS ._rox._ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: scanner-v4-matcher-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "scanner-v4-matcher-tls") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "scanner-v4-matcher-tls") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  ca.pem: |
    {{- ._rox._ca.Cert | nindent 4 }}
  cert.pem: |
    {{- ._rox.scannerV4.matcher._serviceTLS.Cert | nindent 4 }}
  key.pem: |
    {{- ._rox.scannerV4.matcher._serviceTLS.Key | nindent 4 }}
{{- end }}
{{ end -}}
