{{- include "srox.init" . -}}
{{- if (or ._rox.scannerV4._indexerEnabled ._rox.scannerV4._matcherEnabled ._rox.scannerV4._dbEnabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-v4
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "serviceaccount" "scanner-v4") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "serviceaccount" "scanner-v4") | nindent 4 }}
imagePullSecrets:
{{- range $secretName := ._rox.imagePullSecrets._names }}
- name: {{ quote $secretName }}
{{- end }}
{{- end }}
