{{- include "srox.init" . -}}

{{- if not ._rox.scanner.disable -}}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scanner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "networkpolicy" "scanner") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "networkpolicy" "scanner") | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: scanner
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: central
{{ if or (eq ._rox.scanner.mode "slim") ._rox.env.openshift }}
  - from:
    - podSelector:
        matchLabels:
          app: sensor
{{ end }}
    ports:
    - port: 8080
      protocol: TCP
    - port: 8443
      protocol: TCP
  policyTypes:
    - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scanner-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "networkpolicy" "scanner-db") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "networkpolicy" "scanner-db") | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: scanner-db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: scanner
    ports:
    - port: 5432
      protocol: TCP
  policyTypes:
    - Ingress

{{ end -}}

{{ if ._rox.scanner.exposeMonitoring }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scanner-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "networkpolicy" "scanner-monitoring") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "networkpolicy" "scanner-monitoring") | nindent 4 }}
spec:
  ingress:
  - ports:
    - port: 9090
      protocol: TCP
  podSelector:
    matchLabels:
      app: scanner
  policyTypes:
    - Ingress
{{ end }}
