{{- include "srox.init" . -}}
{{- if ._rox.scannerV4._dbEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-v4-db
  namespace: {{ .Release.Namespace }}
  labels:
    app: scanner-v4-db
    {{- include "srox.labels" (list . "deployment" "scanner-v4-db") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "deployment" "scanner-v4-db") | nindent 4 }}
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: scanner-v4-db
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: scanner-v4-db
        {{- include "srox.podLabels" (list . "deployment" "scanner-v4-db") | nindent 8 }}
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "5432"
        {{- include "srox.podAnnotations" (list . "deployment" "scanner-v4-db") | nindent 8 }}
        {{- if eq ._rox.env.openshift 4 }}
        openshift.io/required-scc: nonroot-v2
        {{- end }}
    spec:
      {{- if ._rox.scannerV4.db._nodeSelector }}
      nodeSelector:
        {{- ._rox.scannerV4.db._nodeSelector | nindent 8 }}
      {{- end }}
      {{- if ._rox.scannerV4.db.tolerations }}
      tolerations:
        {{- toYaml ._rox.scannerV4.db.tolerations | nindent 8 }}
      {{- end }}
      affinity:
        {{- toYaml ._rox.scannerV4.db.affinity | nindent 8 }}
      {{- if ._rox.scannerV4.db.hostAliases }}
      hostAliases: {{ toYaml ._rox.scannerV4.db.hostAliases | nindent 8 }}
      {{- end }}
      serviceAccountName: scanner-v4
      terminationGracePeriodSeconds: 120
      initContainers:
      {{- if ._rox._securedClusterCertRefresh }}
      - {{ include "srox.tlsCertsInitContainer" (list .) | indent 8 | trim }}
      {{- end }}
      - name: init-db
        image: {{ ._rox.scannerV4.db.image.fullRef | quote }}
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"
        - name: POSTGRES_PASSWORD_FILE
          value: "/run/secrets/stackrox.io/secrets/password"
{{- if ._rox.env.centralServices }}
        - name: SCANNER_DB_INIT_BUNDLE_ENABLED
          value: "true"
{{- end }}
        command:
        - init-entrypoint.sh
        volumeMounts:
        - name: disk
          mountPath: /var/lib/postgresql/data
        - name: scanner-v4-db-password
          mountPath: /run/secrets/stackrox.io/secrets
          readOnly: true
        resources:
          {{- ._rox.scannerV4.db._resources | nindent 10 }}
      containers:
      - name: db
        image: {{ ._rox.scannerV4.db.image.fullRef | quote }}
        env:
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"
        {{- include "srox.envVars" (list . "deployment" "scanner-v4-db" "db") | nindent 8 }}
        ports:
        - name: tcp-postgresql
          containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - -e
            - |
              exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          {{- ._rox.scannerV4.db._resources | nindent 10 }}
        volumeMounts:
        - name: disk
          mountPath: /var/lib/postgresql/data
        - name: config-volume
          mountPath: /etc/stackrox.d/config/
        - name: certs
          mountPath: /run/secrets/stackrox.io/certs
        - name: shared-memory
          mountPath: /dev/shm
      securityContext:
        fsGroup: 70
        runAsUser: 70
        runAsNonRoot: true
        runAsGroup: 70
      volumes:
      - name: disk
        {{- toYaml ._rox.scannerV4.db.persistence._volumeCfg | nindent 8 }}
      - name: config-volume
        configMap:
          name: {{ default "scanner-v4-db-config" ._rox.scannerV4.db.configOverride }}
      {{- if ._rox._securedClusterCertRefresh }}
      - name: certs
        emptyDir: {}
      - name: certs-legacy
        secret:
          secretName: scanner-v4-db-tls
          optional: true
          items:
          - key: cert.pem
            path: server.crt
          - key: key.pem
            path: server.key
          - key: ca.pem
            path: root.crt
      - name: certs-new
        secret:
          secretName: tls-cert-scanner-v4-db
          optional: true
          items:
          - key: cert.pem
            path: server.crt
          - key: key.pem
            path: server.key
          - key: ca.pem
            path: root.crt
      {{- else }}
      - name: certs
        secret:
          secretName: scanner-v4-db-tls
          defaultMode: 0640
          items:
          - key: cert.pem
            path: server.crt
          - key: key.pem
            path: server.key
          - key: ca.pem
            path: root.crt
      {{- end }}
      - name: shared-memory
        emptyDir:
          medium: Memory
          sizeLimit: 750Mi
      - name: scanner-v4-db-password
        secret:
          secretName: scanner-v4-db-password
{{- end }}
