# Adds namespace to all resources.
namespace: rhacs-operator-system

# Value of this field is prepended to the names of all resources.
# Note that it should also match with the prefix (text before '-system') of the namespace field above.
namePrefix: rhacs-operator-

# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    app: rhacs-operator

resources:
- ../../default
