{{ if eq .Values.config.createSecrets true}}
apiVersion: v1
kind: Secret
data:
  ca.pem: |-
{{ .Files.Get "secrets/ca.pem" | b64enc | indent 4 }}
  collector-cert.pem: |-
{{ .Files.Get "secrets/collector-cert.pem" | b64enc | indent 4 }}
  collector-key.pem: |-
{{ .Files.Get "secrets/collector-key.pem" | b64enc | indent 4 }}
metadata:
  labels:
    app.kubernetes.io/name: stackrox
    auto-upgrade.stackrox.io/component: sensor
  name: collector-tls
  namespace: stackrox
type: Opaque
{{ end }}
