{{- include "srox.init" . -}}

{{- if ._rox.env.openshift }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-central-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "role" "use-central-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "role" "use-central-scc") | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - nonroot-v2
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: central-use-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "central-use-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "central-use-scc") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-central-scc
subjects:
- kind: ServiceAccount
  name: central
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-token-reviews
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "clusterrole" "create-token-reviews") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "clusterrole" "create-token-reviews") | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: central-token-review
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "clusterrolebinding" "central-token-review") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "clusterrolebinding" "central-token-review") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-token-reviews
subjects:
- kind: ServiceAccount
  name: central
  namespace: {{.Release.Namespace}}
{{- end }}
