{{- include "srox.init" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: central
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "deployment" "central") | nindent 4 }}
    app: central
  annotations:
    {{- include "srox.annotations" (list . "deployment" "central") | nindent 4 }}
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: central
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: central
        {{- include "srox.podLabels" (list . "deployment" "central") | nindent 8 }}
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "8443"
        {{- include "srox.podAnnotations" (list . "deployment" "central") | nindent 8 }}
    spec:
      {{- if ._rox.central._nodeSelector }}
      nodeSelector:
        {{- ._rox.central._nodeSelector | nindent 8 }}
      {{- end }}
      {{- if ._rox.central.tolerations }}
      tolerations:
        {{- toYaml ._rox.central.tolerations | nindent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Central is single-homed, so avoid preemptible nodes.
            - weight: 100
              preference:
                matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: NotIn
                    values:
                    - "true"
            - weight: 50
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/infra
                    operator: Exists
            - weight: 25
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/compute
                    operator: Exists
            # From v1.20 node-role.kubernetes.io/control-plane replaces node-role.kubernetes.io/master (removed in
            # v1.25). We apply both because our goal is not to run pods on control plane nodes for any version of k8s.
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      serviceAccountName: central
      securityContext:
        fsGroup: 4000
        runAsUser: 4000
      containers:
      - name: central
        image: {{ ._rox.central.image.fullRef | quote }}
        command:
          - /stackrox/central-entrypoint.sh
        ports:
          {{- toYaml ._rox.central._containerPorts | nindent 10 }}
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /v1/ping
            port: 8443
        resources:
          {{- ._rox.central._resources | nindent 10 }}
        securityContext:
          capabilities:
            drop: ["NET_RAW"]
          readOnlyRootFilesystem: true
        env:
        - name: ROX_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROX_INIT_TELEMETRY_ENABLED
          value: {{ ._rox.central.disableTelemetry | not | quote }}
        - name: ROX_OFFLINE_MODE
          value: {{ ._rox.env.offlineMode | quote }}
        {{- if and (eq ._rox.env.openshift 4) (not ._rox.env.managedServices) }}
        - name: ROX_ENABLE_OPENSHIFT_AUTH
          value: "true"
        {{- end }}
        {{- if ._rox.env.managedServices }}
        - name: ROX_MANAGED_CENTRAL
          value: "true"
        {{- end }}
        {{- include "srox.envVars" (list . "deployment" "central" "central") | nindent 8 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log/stackrox/
        - name: central-tmp-volume
          mountPath: /tmp
        - name: central-etc-ssl-volume
          mountPath: /etc/ssl
        - name: central-etc-pki-volume
          mountPath: /etc/pki/ca-trust
        - name: central-certs-volume
          mountPath: /run/secrets/stackrox.io/certs/
          readOnly: true
        - name: central-default-tls-cert-volume
          mountPath: /run/secrets/stackrox.io/default-tls-cert/
          readOnly: true
        - name: central-htpasswd-volume
          mountPath: /run/secrets/stackrox.io/htpasswd/
          readOnly: true
        - name: central-jwt-volume
          mountPath: /run/secrets/stackrox.io/jwt/
          readOnly: true
        - name: additional-ca-volume
          mountPath: /usr/local/share/ca-certificates/
          readOnly: true
        - name: central-license-volume
          mountPath: /run/secrets/stackrox.io/central-license/
          readOnly: true
        - name: stackrox-db
          mountPath: /var/lib/stackrox
        - name: central-config-volume
          mountPath: /etc/stackrox
        - name: proxy-config-volume
          mountPath: /run/secrets/stackrox.io/proxy-config/
          readOnly: true
        - name: endpoints-config-volume
          mountPath: /etc/stackrox.d/endpoints/
          readOnly: true
        {{- if ._rox.centralDB.enabled }}
        - name: central-db-password
          mountPath: /run/secrets/stackrox.io/db-password
        {{- end }}
        {{- range $extraMount := (default list ._rox.central.extraMounts) }}
        - name: {{ $extraMount.name }}
          {{- $extraMount.mount | toYaml | nindent 10 }}
        {{- end }}
        {{- include "srox.injectedCABundleVolumeMount" . | nindent 8 }}
      volumes:
      - name: varlog
        emptyDir: {}
      - name: central-tmp-volume
        emptyDir: {}
      - name: central-etc-ssl-volume
        emptyDir: {}
      - name: central-etc-pki-volume
        emptyDir: {}
      - name: central-certs-volume
        secret:
          secretName: central-tls
      - name: central-default-tls-cert-volume
        secret:
          secretName: {{ default "central-default-tls-cert" ._rox.central.defaultTLS.reference }}
          optional: true
      - name: central-htpasswd-volume
        secret:
          secretName: central-htpasswd
          optional: true
      - name: central-jwt-volume
        secret:
          secretName: central-tls
          items:
            - key: jwt-key.pem
              path: jwt-key.pem
      - name: additional-ca-volume
        secret:
          secretName: additional-ca
          optional: true
      - name: central-license-volume
        secret:
          secretName: central-license
          optional: true
      - name: central-config-volume
        configMap:
          name: central-config
          optional: true
      - name: proxy-config-volume
        secret:
          secretName: proxy-config
          optional: true
      - name: endpoints-config-volume
        configMap:
          name: central-endpoints
      {{- if ._rox.centralDB.enabled }}
      - name: central-db-password
        secret:
          secretName: central-db-password
      {{- end }}
      - name: stackrox-db
        {{- toYaml ._rox.central.persistence._volumeCfg | nindent 8 }}
      {{- range $extraMount := (default list ._rox.central.extraMounts) }}
      - name: {{ $extraMount.name }}
        {{- $extraMount.source | toYaml | nindent 8 }}
      {{- end }}
      {{- include "srox.injectedCABundleVolume" . | nindent 6 }}
