{{- include "srox.init" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "configmap" "central-config") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "configmap" "central-config") | nindent 4 }}
data:
  central-config.yaml: |
    {{- ._rox.central._config | nindent 4 }}
    {{- if ._rox.central.db.enabled }}
    centralDB:
      {{- if ._rox.central.db.preexisting }}
      source: {{ ._rox.central.db.source.connectionString }} statement_timeout={{ ._rox.central.db.source.statementTimeoutMs }} pool_min_conns={{ ._rox.central.db.source.minConns }} pool_max_conns={{ ._rox.central.db.source.maxConns }}
      {{- else }}
      source: >
        host=central-db.{{ .Release.Namespace }}.svc
        port=5432
        user=postgres
        sslmode={{- if eq .Release.Namespace "stackrox" }}verify-full{{- else }}verify-ca{{- end }}
        sslrootcert=/run/secrets/stackrox.io/certs/ca.pem
        statement_timeout={{ ._rox.central.db.source.statementTimeoutMs }}
        pool_min_conns={{ ._rox.central.db.source.minConns }}
        pool_max_conns={{ ._rox.central.db.source.maxConns }}
      {{- end }}
    {{- end }}
