{{- include "srox.init" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: central-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "central-token") | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: central
    {{- include "srox.annotations" (list . "secret" "central-token") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: kubernetes.io/service-account-token
