{{- include "srox.init" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "configmap" "central-config") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "configmap" "central-config") | nindent 4 }}
data:
  central-config.yaml: |
    {{- ._rox.central._config | nindent 4 }}
    centralDB:
      source: >
        host=central-db.{{ .Release.Namespace }}.svc
        port=5432
        user=postgres
        sslmode={{- if eq .Release.Namespace "stackrox" }}verify-full{{- else }}verify-ca{{- end }}
        sslrootcert=/run/secrets/stackrox.io/certs/ca.pem
        statement_timeout=600000
        pool_min_conns=1
        pool_max_conns=90
