{{- include "srox.init" . -}}

{{- if ._rox.env.openshift }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: central-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "role" "central-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "role" "central-scc") | nindent 4 }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - nonroot-v2
  {{- if ._rox.central.persistence.hostPath }}
  - hostmount-anyuid
  {{- end }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: central-use-scc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "central-use-scc") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "central-use-scc") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: central-scc
subjects:
- kind: ServiceAccount
  name: central
  namespace: {{.Release.Namespace}}
{{- end }}
