{{- include "srox.init" . -}}

{{- if ._rox.central.exposure.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: central
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "route" "central") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "route" "central") | nindent 4 }}
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: central
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: central-mtls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "route" "central-mtls") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "route" "central-mtls") | nindent 4 }}
spec:
  host: "central.{{ .Release.Namespace }}"
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: central
---
{{- end }}

{{- if ._rox.central.exposure.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "srox.annotations" (list . "service" "central-loadbalancer") | nindent 4 }}
    cloud.google.com/app-protocols: '{"api": "HTTPS"}'
    service.alpha.kubernetes.io/app-protocols: '{"api": "HTTPS"}'
  name: central-loadbalancer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "service" "central-loadbalancer") | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: api
{{- if ._rox.central.exposure.nodePort.port }}
    nodePort: {{ ._rox.central.exposure.nodePort.port }}
{{- end }}
  selector:
    app: central
---
{{- end }}

{{- if ._rox.central.exposure.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: central-loadbalancer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "service" "central-loadbalancer") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "service" "central-loadbalancer") | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ ._rox.central.exposure.loadBalancer.port }}
    targetPort: api
  selector:
    app: central
---
{{- end}}
