{{- include "srox.init" . -}}

{{- if and ._rox.centralDB.enabled (not ._rox.centralDB.preexisting) ._rox.system.enablePodSecurityPolicies }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-central-db-psp") }}
  labels:
    {{- include "srox.labels" (list . "clusterrole" "stackrox-central-db-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "clusterrole" "stackrox-central-db-psp") | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "srox.globalResourceName" (list . "stackrox-central-db") }}
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stackrox-central-db-psp
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "stackrox-central-db-psp") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "stackrox-central-db-psp") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "srox.globalResourceName" (list . "stackrox-central-db-psp") }}
subjects:
  - kind: ServiceAccount
    name: central-db
    namespace: {{.Release.Namespace}}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "srox.globalResourceName" (list . "stackrox-central-db") }}
  labels:
    {{- include "srox.labels" (list . "podsecuritypolicy" "stackrox-central-db") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "podsecuritypolicy" "stackrox-central-db") | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'hostPath'
  {{- if ._rox.central.persistence.hostPath }}
  allowedHostPaths:
    {{- /* TODO(ROX-9807): Use a designated path for central-db for now. Need to move hostPath from central to central-db */}}
    - pathPrefix: {{._rox.central.persistence.hostPath}}-db
  {{- end}}
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      - min: 70
        max: 70
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 70
        max: 70
{{- end }}
