{{- include "srox.init" . -}}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: central-sts-config-reader
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "srox.annotations" (list . "role" "central-sts-config-reader") | nindent 4 }}
  labels:
    {{- include "srox.labels" (list . "role" "central-sts-config-reader") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["aws-cloud-credentials", "gcp-cloud-credentials"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: central-sts-config-reader
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "central-sts-config-reader") | nindent 4 }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "central-sts-config-reader") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: central
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: central-sts-config-reader
  apiGroup: rbac.authorization.k8s.io
