{{- include "srox.init" . -}}

{{ if ._rox.central._defaultTLS }}

apiVersion: v1
kind: Secret
metadata:
  name: central-default-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "central-default-tls-cert") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "central-default-tls-cert") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- ._rox.central._defaultTLS.Cert | nindent 4 }}
  tls.key: |
    {{- ._rox.central._defaultTLS.Key | nindent 4 }}

{{- end }}
