{{- include "srox.init" . -}}

apiVersion: v1
kind: Service
metadata:
  name: central
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "service" "central") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "service" "central") | nindent 4 }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: api
  selector:
    app: central
  type: ClusterIP

{{ if ._rox.env.istio }}
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: central-internal-no-istio-mtls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "destinationrule" "central-internal-no-istio-mtls") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "destinationrule" "central-internal-no-istio-mtls") | nindent 4 }}
    stackrox.io/description: "Disable Istio mTLS for port 443, since StackRox services use built-in mTLS."
spec:
  host: central.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 443
        tls:
          mode: DISABLE
{{ end }}
