{{- include "srox.init" . -}}

{{- if not ._rox.scanner.disable -}}

{{- if and ._rox.scanner._serviceTLS ._rox._ca -}}

apiVersion: v1
kind: Secret
metadata:
  name: scanner-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "scanner-tls") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "scanner-tls") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  ca.pem: |
    {{- ._rox._ca.Cert | nindent 4 }}
  cert.pem: |
    {{- ._rox.scanner._serviceTLS.Cert | nindent 4 }}
  key.pem: |
    {{- ._rox.scanner._serviceTLS.Key | nindent 4 }}

{{- end }}

---

{{ if and ._rox.scanner._dbServiceTLS ._rox._ca -}}

apiVersion: v1
kind: Secret
metadata:
  name: scanner-db-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "scanner-db-tls") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "scanner-db-tls") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  ca.pem: |
    {{- ._rox._ca.Cert | nindent 4 }}
  cert.pem: |
    {{- ._rox.scanner._dbServiceTLS.Cert | nindent 4 }}
  key.pem: |
    {{- ._rox.scanner._dbServiceTLS.Key | nindent 4 }}

{{- end -}}

{{ end -}}
