{{- include "srox.init" . -}}

{{- if and ._rox.monitoring ._rox.monitoring.openshift ._rox.monitoring.openshift.enabled -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: central-prometheus-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "role" "central-prometheus-k8s") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "role" "central-prometheus-k8s") | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: central-prometheus-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "rolebinding" "central-prometheus-k8s") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "central-prometheus-k8s") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: central-prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "central-monitor-{{ .Release.Name }}-{{ .Release.Namespace }}"
  namespace: openshift-monitoring
  labels:
    {{- include "srox.labels" (list . "servicemonitor" (print "central-monitor-" .Release.Name "-" .Release.Namespace )) | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "servicemonitor" (print "central-monitor-" .Release.Name "-" .Release.Namespace )) | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    path: metrics
    port: monitoring-tls
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
      keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
      serverName: "central.{{ .Release.Namespace }}.svc"
  selector:
    matchLabels:
      app.kubernetes.io/component: central
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhacs-central-auth-reader
  namespace: kube-system
  labels:
    {{- include "srox.labels" (list . "rolebinding" "rhacs-central-auth-reader") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "rolebinding" "rhacs-central-auth-reader") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: central
    namespace: "{{ .Release.Namespace }}"

{{- end -}}
