name: Add any new Pull Request to OSS Triaging project
on:
  pull_request_target:
    types: [opened, reopened]

env:
  EXTERNAL_PR_LABEL: external-contributor

jobs:
  check-pr-if-external:
    name: Add external label to pull request if outside StackRox
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
      BASE_REPO: ${{ github.repository }}
      HEAD_REPO: ${{ github.event.pull_request.head.user.login }}/${{ github.event.pull_request.head.repo.name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - id: check-external-pr
        run: |
          set -uo pipefail
          if [[ "$BASE_REPO" != "$HEAD_REPO" ]]; then
            gh pr edit \
              "${{ github.event.pull_request.number }}" \
              --add-label "${EXTERNAL_PR_LABEL}"
          fi
