name: Check CRD Compatibility
on:
  push:
    tags:
    - '*'
    branches:
    - master
    - release-*
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  check-crd-compatibility:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.4.8
      volumes:  # job-preamble deletes unused host runner files under /mnt
      - /usr:/mnt/usr
      - /opt:/mnt/opt
    outputs:
      released_version: ${{ steps.get_previous_released_version.outputs.released_version }}
    steps:
    - name: Checkout stackrox/stackrox
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

    - name: Checkout crd-schema-checker
      uses: actions/checkout@v4
      with:
        repository: openshift/crd-schema-checker
        path: .crd-schema-checker
        ref: 9c9f5f57c9f9ea4dba41d9eec5c365a622f08417 # 2025-04-08

    - name: Build crd-schema-checker
      run: |
        make -C .crd-schema-checker

    - name: Get previous released version
      id: get_previous_released_version
      run: |
        make -C operator bundle-post-process
        released_version="$(make --no-print-directory -C operator replaced-version)"
        echo "released_version=$released_version" >> "$GITHUB_OUTPUT"

    - name: Checkout previous released version
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ steps.get_previous_released_version.outputs.released_version }}
        path: .old-stackrox

    - name: Run crd-schema-checker for platform operator
      run: |
        old_path=.old-stackrox/operator/config/crd/bases
        new_path=operator/config/crd/bases
        sc_file=platform.stackrox.io_securedclusters.yaml
        central_file=platform.stackrox.io_centrals.yaml
        .crd-schema-checker/crd-schema-checker check-manifests --existing-crd-filename=$old_path/$sc_file --new-crd-filename=$new_path/$sc_file
        .crd-schema-checker/crd-schema-checker check-manifests --existing-crd-filename=$old_path/$central_file --new-crd-filename=$new_path/$central_file

    - name: Run crd-schema-checker for config operator
      run: |
        old_path=.old-stackrox/config-controller/config/crd/bases
        new_path=config-controller/config/crd/bases
        policy_file=config.stackrox.io_securitypolicies.yaml
        .crd-schema-checker/crd-schema-checker check-manifests --existing-crd-filename=$old_path/$policy_file --new-crd-filename=$new_path/$policy_file
