
name: emailsender-central-compatibility

on:
  push:
    branches:
      - master
    paths:
      - 'central/notifiers/email/**'
      - 'central/notifiers/acscsemail/**'
      - 'central/auth/m2m/**'
      - '.github/workflows/emailsender-central-compatibility.yaml'

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'central/notifiers/email/**'
      - 'central/notifiers/acscsemail/**'
      - 'central/auth/m2m/**'
      - '.github/workflows/emailsender-central-compatibility.yaml'

jobs:
  e2e-test-on-kind:
    timeout-minutes: 60
    name: "Test on kind cluster"
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.head.repo.fork }} # do not run for PRs from forks
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Cancel Previous Runs
        uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_RHACS_ENG_RO_USERNAME }}
          password: ${{ secrets.QUAY_RHACS_ENG_RO_PASSWORD }}
      - name: Checkout stackrox/acs-fleet-manager repository
        uses: actions/checkout@v6
        with:
          repository: stackrox/acs-fleet-manager
          path: acs-fleet-manager
          ref: main
          fetch-depth: 0
      - name: Checkout stackrox/stackrox repository
        uses: actions/checkout@v6
        with:
          repository: stackrox/stackrox
          ref: ${{ github.event.pull_request.head.sha }}
          path: stackrox
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: stackrox/go.mod
          cache: false
      - name: Cache go module
        uses: actions/cache@v5
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('stackrox/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: ./stackrox/.github/actions/job-preamble
        with:
          free-disk-space: 40
      - name: Create Kind cluster"
        uses: helm/kind-action@v1
        with:
          cluster_name: kind
      - name: Run Test
        env:
          IMG_WAIT_TIMEOUT_SECONDS: 2100
        run: acs-fleet-manager/scripts/ci/central_compatibility/entrypoint.sh
      - name: Upload logs
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: logs-directory-${{ github.sha }}
          path: logs/
          retention-days: 3
