name: Auto-retest Konflux Builds

on:
  check_run:
    types: [completed]
  pull_request:
    types: [synchronize]

jobs:
  retest-failed-builds:
    uses: stackrox/actions/konflux/auto-retest/retest-failed-builds.yml@v1
    with:
      max_retries: 3
      check_name_suffix: '-on-push'
