name: "Release: Notify when PR is added or removed from milestone"
on:
  pull_request:
    types: [milestoned, demilestoned]

env:
  ACCEPT_RAW: "Accept: application/vnd.github.v3.raw"
  GH_TOKEN: ${{ github.token }}
  GH_NO_UPDATE_NOTIFIER: 1

jobs:
  properties:
    name: Read repository properties
    runs-on: ubuntu-22.04
    outputs:
      docs-repository: ${{ steps.properties.outputs.docs-repository }}
      slack-channel: ${{ fromJSON(format('["{0}","{1}"]', steps.properties.outputs.dry-slack-channel, steps.properties.outputs.slack-channel))[github.repository == 'stackrox/stackrox'] }}
      jira-project: ${{ steps.properties.outputs.jira-project }}
    steps:
      - name: Read workflow properties file
        id: properties
        env:
          PROPERTIES_URL: /repos/${{ github.repository }}/contents/.github/properties?ref=${{ github.event.repository.default_branch }}
        run: gh api -H "$ACCEPT_RAW" "$PROPERTIES_URL" >> "$GITHUB_OUTPUT"

  notify:
    runs-on: ubuntu-22.04
    needs: [properties]
    steps:
      - name: Determine Jira context for PR
        id: context
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
            if [ "${{ github.event.action}}" = "milestoned" ]; then
              EVENT_ACTION="added to"
              EVENT_ICON=":white_check_mark:"
              echo "call-to-action=:arrow_right: Release Engineers <!subteam^S051ZQXP97X|acs-release-eng> and <!subteam^S04TXGK6B32|acs-eng-staff>: Review whether this PR meets the criteria for being included in the release." >> "${GITHUB_OUTPUT}"
            else
              EVENT_ACTION="removed from"
              EVENT_ICON=":x:"
              echo "call-to-action=:arrow_right: FYI, No action required" >> "${GITHUB_OUTPUT}"
            fi

            echo "pr-info=${EVENT_ICON} <${{ github.event.pull_request.html_url }}|${PR_TITLE}> (Author: ${{ github.event.pull_request.user.login }}) was ${EVENT_ACTION} milestone <${{ github.event.milestone.html_url }}|${{ github.event.milestone.title }}>." >> "${GITHUB_OUTPUT}"

            ISSUE_ID="$(echo "${PR_TITLE}" | grep --only-matching 'ROX-[0-9]\+' || true)"
            if [ -n "${ISSUE_ID}" ]; then
              JIRA_INFO="$(curl \
                -sSL \
                --location "https://issues.redhat.com/rest/api/2/issue/${ISSUE_ID}" \
                --header "Authorization: Bearer ${{ secrets.JIRA_TOKEN }}" \
              | jq -r '{ key: .key, summary: .fields.summary, priority: .fields.priority.name, assignee: .fields.assignee.displayName, status: .fields.status.name, type: .fields.issuetype.name }')"

              KEY="$(echo "${JIRA_INFO}" | jq -r .key)"
              SUMMARY="$(echo "${JIRA_INFO}" | jq -r .summary)"
              PRIORITY="$(echo "${JIRA_INFO}" | jq -r .priority)"
              ASSIGNEE="$(echo "${JIRA_INFO}" | jq -r .assignee)"
              STATUS="$(echo "${JIRA_INFO}" | jq -r .status)"
              TYPE="$(echo "${JIRA_INFO}" | jq -r .type)"

              # shellcheck disable=SC2028
              echo "jira-info=<https://issues.redhat.com/browse/${KEY}|${KEY}: ${SUMMARY}>\n>Type: \`${TYPE}\`\n>Assignee: \`${ASSIGNEE}\`\n>Status: \`${STATUS}\`\n>Priority: \`${PRIORITY}\`" >> "${GITHUB_OUTPUT}"
            else
              echo "jira-info=:exclamation: We could not find a Jira issue for this PR." >> "${GITHUB_OUTPUT}"
            fi

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "${{ needs.properties.outputs.slack-channel }}"
            text: "${{ steps.context.outputs.pr-info }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ steps.context.outputs.pr-info }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ steps.context.outputs.call-to-action }}"
              - type: "divider"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "${{ steps.context.outputs.jira-info}}"
