name: Auto /retest
on:
  workflow_dispatch:
  schedule:
  - cron: 5,15,25,35,45,55 * * * *
concurrency:
  group: Auto /retest
  cancel-in-progress: false
jobs:
  retest:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          tools/retest

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Retest
      env:
        GITHUB_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
      run: cd tools/retest && go run ./...
