name: Auto /retest
on:
  workflow_dispatch:
  schedule:
  - cron: 5,15,25,35,45,55 * * * *
concurrency:
  group: Auto /retest
  cancel-in-progress: false
jobs:
  retest:
    if:  ${{ github.repository_owner == 'stackrox' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        sparse-checkout: |
          .github
          tools/retest

    - name: Setup Go environment
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Retest
      env:
        GITHUB_TOKEN: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
      run: cd tools/retest && go run ./...
