name: Roxctl Image Scan

on:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read

jobs:
  roxctl:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
    - name: Download roxctl
      env:
        ROX_API_TOKEN: ${{ secrets.STACKROX_CI_INSTANCE_API_KEY }}
        ROX_CENTRAL_ADDRESS: ${{ secrets.STACKROX_CI_INSTANCE_CENTRAL_HOST }}
      run:  curl -sSLO -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ADDRESS:443/api/cli/download/roxctl-linux -o roxctl && chmod +x ./roxctl
    - name: Image scan
      env:
        ROX_API_TOKEN: ${{ secrets.STACKROX_CI_INSTANCE_API_KEY }}
        ROX_CENTRAL_ADDRESS: ${{ secrets.STACKROX_CI_INSTANCE_CENTRAL_HOST }}
      run: ./roxctl image scan -e $ROX_CENTRAL_ADDRESS:443 -i quay.io/stackrox-io/main -o table
    - name: Image check
      env:
        ROX_API_TOKEN: ${{ secrets.STACKROX_CI_INSTANCE_API_KEY }}
        ROX_CENTRAL_ADDRESS: ${{ secrets.STACKROX_CI_INSTANCE_CENTRAL_HOST }}
      run: ./roxctl image check -e $ROX_CENTRAL_ADDRESS:443 -i quay.io/stackrox-io/main -o junit > check.xml && ./roxctl image check -e $ROX_CENTRAL_ADDRESS:443 -i quay.io/stackrox-io/main -o table
    - name: Create test summary
      uses: test-summary/action@dist
      with:
        paths: check.xml
      if: always()
