name: Scanner dev vulnerability update
on:
  schedule:
  - cron: "30 */4 * * *"

jobs:
  upload-dev-vulnerabilities:
    runs-on: ubuntu-latest
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.3.66
      volumes:
        - /tmp:/tmp # make sure Claircore blob can access tmp folder
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: ./.github/actions/job-preamble

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SA_STACKROX_HUB_VULN_DUMP_UPLOADER }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Update vulnerabilities
      env:
        STACKROX_NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        STACKROX_NVD_API_CALL_INTERVAL: 6s
      run: |
        if [ ! -d "scanner" ]; then
          echo "Scanner directory not found. Terminating current step."
          exit 1
        fi

        make -C scanner bin/updater
        go clean -cache -modcache
        ./scanner/bin/updater -output-dir=dev
        gsutil cp -r "dev" "gs://definitions.stackrox.io/v4/vulnerability-bundles"

  send-notification:
    needs:
    - upload-dev-vulnerabilities
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Send Slack notification on workflow failure
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"<${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}|Workflow ${{ github.workflow }}> failed in repository ${{ github.repository }}: Failed to update vulnerabilities"}' ${{ secrets.SLACK_ONCALL_SCANNER_WEBHOOK }}
