name: Scanner dev vulnerability update
on:
  schedule:
  - cron: "30 */4 * * *"
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  workflow_dispatch:
    inputs:
      job:
        type: choice
        description: "Choose the NVD source"
        options:
        - nvd-api
        - nvd-feeds
        required: true
        default: nvd-api

jobs:
  build-updater:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request' &&
       contains(github.event.pull_request.labels.*.name, 'pr-update-scanner-vulns'))
    container:
      image: quay.io/stackrox-io/apollo-ci:stackrox-test-0.4.2
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}
    - uses: ./.github/actions/cache-go-dependencies

    - name: Build updater
      run: |
        make tag
        make -C scanner bin/updater

    - uses: ./.github/actions/upload-artifact-with-retry
      with:
        name: updater
        path: scanner/bin/updater
        if-no-files-found: error

  download-nvd:
    runs-on: ubuntu-latest
    env:
      JOB: ${{ github.event.inputs.job || 'nvd-api' }}
    if: >
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request' &&
       contains(github.event.pull_request.labels.*.name, 'pr-update-scanner-vulns'))
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Download NVD
      run: |
        set -eu
        since_time=$(date -u -d '24 hours ago' '+%a, %d %b %Y %H:%M:%S GMT')
        if [ "$JOB" = "nvd-api" ]; then
            url="https://definitions.stackrox.io/v4/nvd/nvd-api.zip"
          else
            url="https://definitions.stackrox.io/v4/nvd/nvd-feeds.zip"
          fi

        code=$(curl \
            -o nvd.zip \
            -w "%{http_code}" \
            -H "If-Modified-Since: $since_time" \
            "$url")

        echo "code: $code"
        echo "$code" | grep -q 200

    - uses: ./.github/actions/upload-artifact-with-retry
      with:
        name: nvd
        path: nvd.zip
        if-no-files-found: error

  run-updater:
    needs:
    - build-updater
    - download-nvd
    runs-on: ubuntu-latest
    env:
      STACKROX_NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      STACKROX_NVD_API_CALL_INTERVAL: 6s

    steps:
    # Checkout to run ./.github/actions/{download,upload}-artifact-with-retry
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha || github.ref }}

    - uses: ./.github/actions/job-preamble
      with:
        gcp-account: ${{ secrets.GCP_SERVICE_ACCOUNT_STACKROX_CI }}

    - name: Free up disk space
      shell: bash
      run: |
        set +e
        set -x
        df -h
        for delete in /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL; do
          rm -rf "${delete:?}"
        done
        df -h

    - name: Set MANUAL_URL
      id: set-manual-url
      run: |
        if [ "${{ github.event_name }}" == "schedule" ]; then
          echo "MANUAL_URL=https://raw.githubusercontent.com/stackrox/stackrox/master/scanner/updater/manual/vulns.yaml" >> "$GITHUB_ENV"
        else
          echo "MANUAL_URL=https://raw.githubusercontent.com/stackrox/stackrox/${{ github.event.pull_request.head.sha }}/scanner/updater/manual/vulns.yaml" >> "$GITHUB_ENV"
        fi

    - uses: ./.github/actions/download-artifact-with-retry
      with:
        name: updater
        path: /usr/local/bin

    - uses: ./.github/actions/download-artifact-with-retry
      with:
        name: nvd
        path: .

    - name: Set updater
      run: |
        chmod +x /usr/local/bin/updater
        mkdir vulns

    - name: Run updater (single bundle)
      env:
        STACKROX_NVD_ZIP_PATH: nvd.zip
      run: |
        updater export vulns --manual-url "$MANUAL_URL"

    - name: Run updater (multi bundle)
      env:
        STACKROX_NVD_ZIP_PATH: nvd.zip
      run: |
        updater export --manual-url "$MANUAL_URL" --split bundles
        zip vulns/vulnerabilities.zip bundles/*.json.zst

    - uses: ./.github/actions/upload-artifact-with-retry
      with:
        name: vulns
        path: vulns
        if-no-files-found: error

  upload-vulnerabilities:
    runs-on: ubuntu-latest
    needs:
    - run-updater
    steps:
    # Checkout to run ./.github/actions/download-artifact-with-retry
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: ./.github/actions/download-artifact-with-retry
      with:
        name: vulns
        path: vulns

    - name: Authenticate with Google Cloud
      if: github.event_name == 'schedule'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SA_STACKROX_HUB_VULN_DUMP_UPLOADER }}

    - name: Authenticate with Google Cloud
      if: github.event_name == 'pull_request'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_SA_CIRCLECI_SCANNER }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Update dev vulnerabilities
      if: github.event_name == 'schedule'
      run: |
        cd vulns
        # Upload development tags for upstream (dev) and downstream (1.0.0).
        gsutil -m cp -r . gs://definitions.stackrox.io/v4/vulnerability-bundles/dev/
        gsutil -m cp -r . gs://definitions.stackrox.io/v4/vulnerability-bundles/1.0.0/

    - name: Update PR vulnerabilities
      if: github.event_name == 'pull_request'
      run: |
        branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        # Replace / with -, so the branch name isn't truncated when pushed to GCS.
        dir=${branch////-}
        case $dir in
        dev|1.0.0)
          echo "Branch $dir is disallowed"
          exit 1
        esac
        cd vulns
        gsutil cp -r . "gs://scanner-v4-test/vulnerability-bundles/$dir"

  send-notification:
    needs:
    - upload-vulnerabilities
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Send Slack notification on workflow failure
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"<${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}|Workflow ${{ github.workflow }}> failed in repository ${{ github.repository }}: Failed to update vulnerabilities"}' ${{ secrets.SLACK_ONCALL_SCANNER_WEBHOOK }}
