name: Triage Report
on:
  workflow_dispatch:
  schedule:
  - cron: 0 5 * * 1
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
jobs:
  triage-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Report to Slack
      env:
        JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_ACS_SUPPORT_TRIAGE_WEBHOOK }}
      run: ./scripts/run-support-triage-report.sh
