name: Update fact version
on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * 1
jobs:
  update-fact:
    if:  ${{ github.repository_owner == 'stackrox' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        ref: master # this is our target branch
        fetch-depth: 0 # we need to fetch all branches
    - name: Checkout fact repo
      uses: actions/checkout@v6
      with:
        repository: stackrox/fact
        path: deps/fact
        fetch-depth: 0 # we need to fetch tags
    - name: Update version
      run: make -sC deps/fact tag | tee FACT_VERSION
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v8
      with:
        token: '${{ secrets.RHACS_BOT_GITHUB_TOKEN }}'
        commit-message: Update FACT_VERSION
        committer: '${{ secrets.RHACS_BOT_GITHUB_USERNAME }} <${{ secrets.RHACS_BOT_GITHUB_EMAIL }}>'
        author: '${{ secrets.RHACS_BOT_GITHUB_USERNAME }} <${{ secrets.RHACS_BOT_GITHUB_EMAIL }}>'
        branch: update_fact_version
        signoff: false
        delete-branch: true
        title: 'chore(fact): Update FACT_VERSION'
        body: |
          Daily update of FACT_VERSION to latest master version
        labels: |
          ci-all-qa-tests
          dependencies
          konflux-build
        team-reviewers: |
          collector-team
        draft: false
    - name: Enable Pull Request Automerge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: '${{ secrets.RHACS_BOT_GITHUB_TOKEN }}'
        pull-request-number: '${{ steps.cpr.outputs.pull-request-number }}'
        merge-method: squash
